import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import AppStateProvider from '@/hooks/state-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '♟️ Chess Game ♟️',
  description: 'Generated by create next app',
  icons: '/chessGame.jpg',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('bg-slate-500', inter.className)}>
        <AppStateProvider>{children}</AppStateProvider>
      </body>
    </html>
  );
}
